############################################################
# +------------------------------------------------------+ #
# |     ___         _      _     ___  _                  | #
# |    / _ \  _  _ (_) __ | |__ / __|| | ___  ___ ___    | #
# |   | (_) || || || |/ _|| / /| (__ | |/ _ \(_-</ -_)   | #
# |    \__\_\ \_,_||_|\__||_\_\ \___||_|\___//__/\___|   | #
# |                                                      | #
# | By: Benz56                                           | #
# +------------------------------------------------------+ #
############################################################

# Blacklist some inventory types from being quick closeable. Find inventory types below:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryType.html
InventoryTypeBlackList:
#- CHEST

# You may invert the above effectively making the blacklist a whitelist.
InventoryTypeBlackListInvert: false

# Only trigger on clicks that are performed with no item in the hand.
EmptyHandOnly: true

# The number of consecutive clicks needed to quick close an inventory.
# E.g. setting the value to 2 will require a double click etc.
ClicksToClose: 1

# The maximum amount of milliseconds between two clicks to be treated as consecutive.
ConsecutiveClicksTimeFrame: 500

# The type of click needed to trigger quick close: LEFT, MIDDLE, or RIGHT
# You may specify multiple by comma separating the types e.g. 'RIGHT, LEFT'
ClickTypeToClose: 'RIGHT'

# By enabling this any inventory with a custom name won't be quick closeable.
IgnoreNamedInventories: false

# Update Checker.
# Enable or disable the update checker.
UpdateCheckerEnabled: true
# false: All OPs are notified of a new update when they join.
# true: OPs are only notified if they have the quickclose.update permission as well.
# N.B. any user with the quickclose.update permission is notified; OP or not.
UpdateCheckerPermissionOnly: false